name: Localize - Manual Run
on:
  workflow_dispatch:
  
jobs:
  localize:
    runs-on: ubuntu-latest
    steps:  
      - name: Run Localize Action
        uses: reyesp23/gpt-ios-localization@main
        with:
          HEAD_REF: 'develop'
          SOURCE_REF: ${{ github.sha }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          BASE_LANGUAGE: 'en'
          TARGET_LANGUAGES: 'it, es, fr'
          PR_BASE_BRANCH: ${{ github.ref }}
