name: Localize - Release 2 Develop
on:
  create:
    branches:
      - 'release/*'

jobs:
  localize:
    runs-on: ubuntu-latest
    steps:
  
      - name: Run Localize Action
        uses: reyesp23/gpt-ios-localization@main
        with:
          HEAD_REF: ${{ github.sha }}
          SOURCE_REF: 'develop'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          BASE_LANGUAGE: 'en'
          TARGET_LANGUAGES: 'it, es'
          PR_BASE_BRANCH: 'develop'
